### ISSUE TITLE
发布包中缺少了less文件？

### ISSUE THREAD

**Issue by Mikuu** [SSShooter/node-menu#1]
这个插件的发布包中是不是缺少了less文件？我看package.json中的exports只有js和cjs，没有less文件，使用plugin时也没有找到node-menu这个class。

**Comment by SSShooter** [comment]
对不起，漏了一行 `import '@mind-elixir/node-menu/dist/style.css'`

**Comment by Mikuu** [comment]
我添加了那一行，但还是有问题：
```javascript
<script setup>
import MindElixir, { E } from "mind-elixir";
import nodeMenu from '@mind-elixir/node-menu';

import { onMounted } from "vue";

const options = {
  el: '#map',
  nodeMenu: true
}

const minding = () => {
  const mind = new MindElixir(options);
  const rootNode = MindElixir.new("demo");
  mind.install(nodeMenu);
  mind.init(rootNode);

  E(rootNode.id);
};

onMounted(() => {
  minding();
});
</script>

<template>
  <div id="map"></div>
</template>

<style scoped>
@import '../node_modules/@mind-elixir/node-menu/dist/style.css';

#map {
  width: 100vw;
  height: 90vh;
}
</style>
```

<img width="1788" alt="Screen Shot 2023-06-14 at 1 47 19 PM" src="https://github.com/ssshooter/node-menu/assets/11648253/19cd51e9-3431-4cb1-9592-ad464920989e">

我在vue的<style>里面import这个css，vue会自动给css添加唯一属性选择器，就是那个[data-v-652c9c5a]，但位置和html里面又不匹配，所以导致还是找不到node-menu这个class，就还在显示不出node-menu。

我对vue不是很熟，大佬能否指点一下，是不是我的用法不对呀？谢谢

**Comment by Mikuu** [comment]
好的，谢谢
